"""build_project against a fake agents-cli (see conftest.FakeAgentsCli)."""

import io
import zipfile

import pytest
import tomlkit
import yaml

from app.builder import generator
from app.builder.blueprint import load_blueprint, parse_blueprint
from app.builder.generator import BuildError, build_project, project_files, scaffold_command, zip_project
from tests.conftest import MINIMAL_BLUEPRINT, FakeAgentsCli


@pytest.fixture(autouse=True)
def fixed_tools(monkeypatch):
    """Pretend agents-cli, uv and ruff are installed; FakeAgentsCli answers them."""
    monkeypatch.setenv("AGENTS_CLI", "agents-cli")
    monkeypatch.setattr(generator.shutil, "which", lambda name: f"/usr/bin/{name}")


def test_scaffold_command():
    bp = load_blueprint("blueprints/support_team.yml")
    cmd = scaffold_command(bp, generator.Path("/out"))
    assert cmd[:3] == ["agents-cli", "create", "support-team"]
    flags = dict(zip(cmd[3::2], cmd[4::2], strict=False))
    assert flags["--deployment-target"] == "cloud_run"
    assert flags["--root-agent-name"] == "triage"
    assert flags["--region"] == "us-central1"
    assert flags["--output-dir"] == "/out"
    for flag in ("--prototype", "--yes", "--skip-checks"):
        assert flag in cmd
    assert "--agent-gateway" not in cmd


def test_agent_gateway_flag():
    data = yaml.safe_load(MINIMAL_BLUEPRINT)
    data["deployment"] = {"agent_gateway": True}
    assert "--agent-gateway" in scaffold_command(parse_blueprint(yaml.safe_dump(data)), generator.Path("/o"))


def test_agents_cli_command_resolution(monkeypatch):
    monkeypatch.setenv("AGENTS_CLI", "uvx google-agents-cli")
    assert generator.agents_cli_command() == ["uvx", "google-agents-cli"]
    monkeypatch.delenv("AGENTS_CLI")
    monkeypatch.setattr(generator.shutil, "which", lambda name: None)
    assert generator.agents_cli_command()[1:] == ["-m", "google.agents.cli.main"]


def test_build_renders_over_scaffold(tmp_path, fake_cli):
    bp = load_blueprint("blueprints/dice_mcp_agent.yml")
    result = build_project(bp, tmp_path, runner=fake_cli)
    project = tmp_path / "dice-mcp-agent"

    assert result.project_dir == project
    assert "tests/eval/tool_calls.py" in result.files_written
    assert "scaffold placeholder" not in (project / "app/agent.py").read_text()
    assert load_blueprint(project / "blueprint.yml") == bp

    for env_file in (".env", ".env.example"):
        text = (project / env_file).read_text()
        assert "GOOGLE_CLOUD_PROJECT=your-gcp-project-id" in text
        assert text.count("MCP_SERVER_URL=http://127.0.0.1:8080/mcp") == 1

    pyproject = tomlkit.parse((project / "pyproject.toml").read_text())
    assert generator.MCP_REQUIREMENT in pyproject["project"]["dependencies"]
    assert pyproject["project"]["description"] == bp.description
    assert "Generated by agent-builder" in (project / "README.md").read_text()

    # new dependency -> re-lock so the Dockerfile's `uv sync --frozen` sees it
    assert any(c[-1] == "lock" for c in fake_cli.calls)
    assert fake_cli.commands("format"), "rendered python should be formatted"


def test_blueprint_dependencies_added_once(tmp_path, fake_cli):
    data = yaml.safe_load(MINIMAL_BLUEPRINT)
    data["dependencies"] = ["requests>=2.31", "Google-ADK[gcp]>=2.8"]  # adk already present
    build_project(parse_blueprint(yaml.safe_dump(data)), tmp_path, runner=fake_cli)
    deps = tomlkit.parse((tmp_path / "tiny-agent/pyproject.toml").read_text())["project"]["dependencies"]
    assert list(deps) == ["google-adk[gcp]>=2.8.0,<2.9.0", "requests>=2.31"]


def test_no_new_dependencies_no_relock(tmp_path, fake_cli):
    build_project(parse_blueprint(MINIMAL_BLUEPRINT), tmp_path, runner=fake_cli)
    assert not [c for c in fake_cli.calls if c[-1] == "lock"]


def test_lock_failure_is_a_warning(tmp_path):
    cli = FakeAgentsCli(fail_lock=True)
    result = build_project(load_blueprint("blueprints/dice_mcp_agent.yml"), tmp_path, runner=cli)
    assert any("uv lock" in w for w in result.warnings)


def test_existing_project_needs_overwrite(tmp_path, fake_cli):
    bp = parse_blueprint(MINIMAL_BLUEPRINT)
    build_project(bp, tmp_path, runner=fake_cli)
    (tmp_path / "tiny-agent/stale.txt").write_text("old")
    with pytest.raises(FileExistsError):
        build_project(bp, tmp_path, runner=fake_cli)
    build_project(bp, tmp_path, runner=fake_cli, overwrite=True)
    assert not (tmp_path / "tiny-agent/stale.txt").exists()


def test_agents_cli_failure(tmp_path):
    with pytest.raises(BuildError, match="agents-cli create exited with 2:\nError: template not found"):
        build_project(parse_blueprint(MINIMAL_BLUEPRINT), tmp_path, runner=FakeAgentsCli(fail_create=True))


def test_scaffold_missing(tmp_path):
    def silent(cmd, **kwargs):
        import subprocess

        return subprocess.CompletedProcess(cmd, 0, "", "")

    with pytest.raises(BuildError, match="did not produce"):
        build_project(parse_blueprint(MINIMAL_BLUEPRINT), tmp_path, runner=silent)


def test_zip_excludes_local_state(tmp_path, fake_cli):
    result = build_project(parse_blueprint(MINIMAL_BLUEPRINT), tmp_path, runner=fake_cli)
    (result.project_dir / "app/__pycache__").mkdir()
    (result.project_dir / "app/__pycache__/agent.cpython-311.pyc").write_bytes(b"")

    files = project_files(result.project_dir)
    assert ".env.example" in files and "app/agent.py" in files
    assert not [f for f in files if f == ".env" or ".venv" in f or "__pycache__" in f]

    with zipfile.ZipFile(io.BytesIO(zip_project(result.project_dir))) as archive:
        assert sorted(archive.namelist()) == [f"tiny-agent/{f}" for f in files]


def test_next_steps_mention_mcp_env(tmp_path, fake_cli):
    steps = build_project(load_blueprint("blueprints/dice_mcp_agent.yml"), tmp_path, runner=fake_cli).next_steps()
    assert steps[0] == "cd dice-mcp-agent"
    assert any("MCP server URL" in s for s in steps)
    assert steps[-1].startswith("agents-cli deploy")
